### ISSUE TITLE
Is it safe to put api key in front end code? What's the best practice for using it in browser

### ISSUE THREAD

**Issue by AeroXi** [ProjectOpenSea/stream-js#113]

**Comment by fmaduakor** [comment]
The api key should not be extractable for third parties, otherwise other people might use your key and it could get blocked (key sharing is not allowed).
Try to set up a system where your key cannot be used by third parties (e.g. send requests through your backend)

**Comment by itsthedoom** [comment]
@AeroXi, I concur with @fmaduakor 
Additionally 
Do not embed API keys directly in code. API keys that are embedded in code can be accidentally exposed to the public. For example, you may forget to remove the keys from code that you share. Instead of embedding your API keys in your applications, store them in environment variables or in files outside of your application's source tree.

Do not store API keys in files inside your application's source tree. If you store API keys in files, keep the files outside your application's source tree to help ensure your keys do not end up in your source code control system. This is particularly important if you use a public source code management system such as GitHub.

There are multiple resources online that share API key management best practices. 

Please feel free to join our Discord with other web3 BUIDLers https://discord.com/invite/opensea
