### ISSUE TITLE
Is this ready for production use?

### ISSUE THREAD

**Issue by rollue** [ProjectOpenSea/stream-js#76]
Hi, I've been looking at this library and it looks promising.
Is it ready for production use yet?
I've given it a tentative try to set it up but it doesn't seem to work well - maybe there's something missing from the documentation for installation?

**Comment by edgework** [comment]
This is far from ready. Its based on some really bad engineering choices. You should probably give up on it.

**Comment by itsthedoom** [comment]
@rollue this is a beta version of the Stream API, a new websocket-based service that enables developers to receive events as they occur across our marketplace.  

We’ve built the Stream API to support a range of use cases that rely on dynamic data, such as price fluctuation, listings, bids, and ownership changes. Instead of polling for updates, you subscribe to receive events as they occur.

Developer docs: https://docs.opensea.io/reference/stream-api-overview

The Stream API makes it easier to build new features such as:

- Push notifications to alert people when they receive new bids
- Activity feed that provides a timeline of sales from a collection
- A real-time dashboard that visualizes key trends and metrics


Here is an example where we’ve used the Stream API to send events to a Discord webhook: https://github.com/ProjectOpenSea/opensea-stream-discord-webhook

To learn more, check out our blog post: https://nft.mirror.xyz/HhXSvsS7ZhVns6FuJB1rUGP53gW-qDVCv5gfx9cDGco

Reach out on Discord if you have any questions, issues, or feedback. We can’t wait to see what you build! https://discord.gg/opensea 

Closing this ticket, if you need additional help or if this did not answer your question, please feel free to reply.
